steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--no-cache"
      - "-t"
      - "${_GCR_HOSTNAME}/$PROJECT_ID/$REPO_NAME/${_SERVICE_NAME}:$COMMIT_SHA"
      - "--build-arg=REACT_APP_STAGE=prod"
      - "--build-arg=REACT_APP_BACKEND_BASE_URL=https://growychatapp-imvbs5m4uq-an.a.run.app"
      - "--build-arg=REACT_APP_GOOGLE_OAUTH_CLIENT_ID=892433517348-ldkieko7692c89ud3mut1q7mu7k2q1qr.apps.googleusercontent.com"
      - "."
    id: Build

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_GCR_HOSTNAME}/$PROJECT_ID/$REPO_NAME/${_SERVICE_NAME}:$COMMIT_SHA"
    id: Push

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "$_SERVICE_NAME"
      - "--image"
      - "${_GCR_HOSTNAME}/$PROJECT_ID/$REPO_NAME/${_SERVICE_NAME}:$COMMIT_SHA"
      - "--platform=managed"
      - "--region=${_DEPLOY_REGION}"
      - "--allow-unauthenticated"
    id: Deploy
images:
  - "${_GCR_HOSTNAME}/$PROJECT_ID/$REPO_NAME/${_SERVICE_NAME}:$COMMIT_SHA"
